/*
This file contains all would-be-magic-strings in the app.
*/

module.exports = {
	// MISC
	FIREBASE: "https://fresh-sauce.firebaseio.com/",

	// AUTH ACTIONS
	ATTEMPTING_LOGIN: "ATTEMPTING_LOGIN",
	LOGIN_USER: "LOGIN_USER",
	LOGOUT: "LOGOUT",

	// AUTH STATES
	LOGGED_IN: "LOGGED_IN",
	ANONYMOUS: "ANONYMOUS",
	AWAITING_AUTH_RESPONSE: "AWAITING_AUTH_RESPONSE",

	// TRACK ACTIONS
	RECEIVE_TRACKS_DATA: "RECEIVE_TRACKS_DATA",
	PLAY_TRACK: "PLAY_TRACK",
	AWAIT_NEW_TRACK_RESPONSE: "AWAIT_NEW_TRACK_RESPONSE",
	RECEIVE_NEW_TRACK_RESPONSE: "RECEIVE_NEW_TRACK_RESPONSE",
	START_TRACK_EDIT: "START_TRACK_EDIT",
	FINISH_TRACK_EDIT: "FINISH_TRACK_EDIT",
	SUBMIT_TRACK_EDIT: "SUBMIT_TRACK_EDIT",

	// TRACK STATES
	EDITING_TRACK: "EDITING_TRACK",
	SUBMITTING_TRACK: "SUBMITTING_TRACK"

};
