export default {
  // MISC
  FIREBASE: "https://fresh-sauce.firebaseio.com/",

  // AUTH ACTIONS
	AUTH_OPEN: 'AUTH_OPEN',
	AUTH_LOGIN: 'AUTH_LOGIN',
	AUTH_LOGOUT: 'AUTH_LOGOUT',
	AUTH_ANONYMOUS: 'AUTH_ANONYMOUS',
	AUTH_AWAITING_RESPONSE: 'AUTH_AWAITING_RESPONSE',
	AUTH_LOGGED_IN: 'AUTH_LOGGED_IN',


  // TRACK ACTIONS
  RECEIVE_TRACKS_DATA: "RECEIVE_TRACKS_DATA",
  SET_TRACK: "SET_TRACK",
  DELETE_TRACK: "DELETE_TRACK",
  SET_TRACK_POSITION: "SET_TRACK_POSITION",
  STOP_TRACK: "STOP_TRACK",

  // PLAYER ACTIONS
  SET_PLAYERS: "SET_PLAYERS"
}
