export default {
  // MISC
  FIREBASE: "https://fresh-sauce.firebaseio.com/",

  // AUTH ACTIONS
  ATTEMPTING_LOGIN: "ATTEMPTING_LOGIN",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT: "LOGOUT",

  // AUTH STATES
  LOGGED_IN: "LOGGED_IN",
  ANONYMOUS: "ANONYMOUS",
  AWAITING_AUTH_RESPONSE: "AWAITING_AUTH_RESPONSE",

  // TRACK ACTIONS
  RECEIVE_TRACKS_DATA: "RECEIVE_TRACKS_DATA",
  SET_TRACK: "SET_TRACK",
  SET_TRACK_POSITION: "SET_TRACK_POSITION",
  STOP_TRACK: "STOP_TRACK",

  // PLAYER ACTIONS
  SET_PLAYERS: "SET_PLAYERS"
}
